-- =============================================================================
-- VitoUur App - Supabase one-time setup
-- Run this in: Supabase Dashboard -> SQL Editor  (after or instead of the seed)
--
-- IMPORTANT: The app creates all tables automatically on startup (initDatabase)
-- in the public schema. The seed INSERTs you already have are fine as-is.
-- This script only adds:
--   1. the missing 'denah_photos' table
--   2. a public 'vitour' storage bucket + anonymous upload policies
--   3. storage policies so the browser can upload images directly
-- =============================================================================

-- 1. denah_photos table (the app uses it, it was missing from the seed SQL)
CREATE TABLE IF NOT EXISTS public.denah_photos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denah_id INT NOT NULL REFERENCES public.denah(id) ON DELETE CASCADE,
    image_path VARCHAR(500) NOT NULL,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.denah_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.denah_photos FOR SELECT USING (true);

-- 2. 'vitour' storage bucket must be PUBLIC so /uploads/<file> redirects work
INSERT INTO storage.buckets (id, name, public)
VALUES ('vitour', 'vitour', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 3. Allow the browser (anon key) to upload/replace images in the bucket.
DROP POLICY IF EXISTS "Allow anon read vitour" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon insert vitour" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon update vitour" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon delete vitour" ON storage.objects;

CREATE POLICY "Allow anon read vitour"
  ON storage.objects FOR SELECT TO anon
  USING (bucket_id = 'vitour');

CREATE POLICY "Allow anon insert vitour"
  ON storage.objects FOR INSERT TO anon
  WITH CHECK (bucket_id = 'vitour');

CREATE POLICY "Allow anon update vitour"
  ON storage.objects FOR UPDATE TO anon
  USING (bucket_id = 'vitour')
  WITH CHECK (bucket_id = 'vitour');

CREATE POLICY "Allow anon delete vitour"
  ON storage.objects FOR DELETE TO anon
  USING (bucket_id = 'vitour');